# Funding options for The Pink Revolution
# This file is used by GitHub to display sponsor information

# Uncomment and add your funding links when available
# github: [overkor-tek]
# patreon: username
# open_collective: overkor-tek
# ko_fi: username
# custom: ["https://example.com"]

# The Pink Revolution is currently a self-funded organizational initiative
# Future funding options may be added as the project grows

# 💖 The Pink Revolution continues! 💖
